### ISSUE TITLE
how to test your denoising function？

### ISSUE THREAD

**Issue by mornfairy** [sigal-raab/MoDi#3]
Thank you for your outstanding work!  But I don't know how to test your denoising function. How can I input a wild motion and use your algorithm to remove the noise?

**Comment by sigal-raab** [comment]
You should use the Encoder, whose code is not published yet. We plan on publishing the encoder code on June 2023 (delayed due to other commitments). 
As a temporary solution, you can use our Optimizer code, which is already released. The results are good enough for motions that are not extremely out of the distribution on which the network has been trained. 
Let me know if this helps.

**Comment by cyj907** [comment]
Hello, I have tried the inverse optimization using my motion capture data. But the resulting motion is shaky and the feet does not lie on the ground. Is it common to encounter this situation? Is there any advice to make the final motion smooth and stable?

**Comment by Inbal-leibovitch** [comment]
To achieve the best results with the encoder (or the optimizer) the motion capture data needs to be from the same distribution as the training data - e.g. have the same skeleton topology, bone lengths, similar root position values. You may need to align your motion capture data with the training data to achieve this. This should improve the results. 
Hope this is helpful, let me know if you have further questions.

**Comment by cyj907** [comment]
Thank you for your quick reply. I have retargeted the motion capture data to mixamo skeleton and run the preprocess_edges script provided in the repo. I think that the resulting data should be consistent with the training data in distribution. But the reconstructed motion is still floating. I am not sure if I am testing an outlier motion, because it is a dance motion that moves quite fast. Could you offer me more advice on this?

**Comment by SinMDM** [comment]
Dear cyj907, it seems you are doing the correct preprocessing. To provide further assistance, we would need to review your data. Regrettably, this can be a rather time-consuming task and the capacity of our team is fully utilized for other tasks

**Comment by sigal-raab** [comment]
Dear cyj907, it seems you are doing the correct preprocessing. To provide further assistance, we would need to review your data. Regrettably, this can be a rather time-consuming task and the capacity of our team is fully utilized for other tasks

**Comment by cyj907** [comment]
Thank you for your reply. Finally I decide to train MoDi using my own data and see if it is a problem of data distribution. But I have a hard time figuring out the meaning of **edge_list** in **Edge** class in **data.py**. Could you tell me what the numbers mean in the tuple? Is it the index of joint? And the tuple means the edge that connects two joints? If so, what is the corresponding joint orders? I print out the joints in **names_with_root**, but it seems unrelated to **edge_list**. I'd appreciate it very much if you offer me some explanation on the Edge class. Thank you.

**Comment by sigal-raab** [comment]
Let's set up a Zoom meeting where I can explain stuff in detail. 
Please write to my email sigal.raab@gmail.com and let me know your time zone and when you are free.
